spring:
  datasource:
    url: jdbc:mysql://localhost:3306/manager?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  jpa:
    show-sql: true

server:
  servlet:
    context-path: /manager
  port: 8081